version: "3.7"

services:
    mysql:
        image: mysql:8.0.34
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: project
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_PORT: 3306
            PGDATA: "/var/lib/mysql/data/pgdata"
