CREATE TABLE public.categories (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(40) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	deleted_at timestamptz NULL,
	CONSTRAINT categories_name_key UNIQUE (name),
	CONSTRAINT categories_pkey PRIMARY KEY (id)
);


CREATE TABLE public.products (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	code varchar(20) NOT NULL,
	"name" varchar(50) NOT NULL,
	description text NOT NULL,
	price int4 NOT NULL,
	stock int4 NULL,
  	color varchar(30) NULL,
  	talla int4 NULL,
	images jsonb NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	deleted_at timestamptz NULL,
	category_id int8 NOT NULL,
	CONSTRAINT products_code_key UNIQUE (code),
	CONSTRAINT products_pkey PRIMARY KEY (id)
);
CREATE INDEX products_category_id_baea90ee ON public.products USING btree (category_id);
CREATE INDEX products_code_c3d58fe3_like ON public.products USING btree (code varchar_pattern_ops);

-- public.products foreign keys

ALTER TABLE public.products ADD CONSTRAINT products_category_id_baea90ee_fk_ FOREIGN KEY (category_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED;

________________________________________________________________

CREATE TABLE public.users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	cc varchar(50) NOT NULL,
	"name" varchar(50) NOT NULL,
	phone varchar(30) NOT NULL,
	email varchar(100) NOT NULL,
	"password" varchar(80) NOT NULL,
	address text NULL,
	role varchar(30) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	deleted_at timestamptz NULL,
	CONSTRAINT users_cc_key UNIQUE (cc),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE INDEX users_cc_9deced64_like ON public.users USING btree (cc varchar_pattern_ops);

----------------------------------------------

CREATE TABLE public.orders (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	user_id int8 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	deleted_at timestamp NULL,
	CONSTRAINT orders_pkey PRIMARY KEY (id)
);
CREATE INDEX orders_user_id_f4b83aa1 ON public.orders USING btree (user_id);
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_f4b83aa1_fk_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;

----------------------------------------------

CREATE TABLE public.orders_products (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    amount int4 NOT NULL,
    price int4 NOT NULL,
    created_at timestamptz NOT NULL,
	  updated_at timestamptz NOT NULL,
	  deleted_at timestamp NULL,
    order_id int8 NOT NULL,
	  product_id int8 NOT NULL,
    CONSTRAINT orders_products_pkey PRIMARY KEY (id)
);
CREATE INDEX orders_products_order_id_7392030e ON public.orders_products USING btree (order_id);
CREATE INDEX orders_products_product_id_90f4ac8b ON public.orders_products USING btree (product_id);

ALTER TABLE public.orders_products ADD CONSTRAINT orders_products_order_id_7392030e_fk_order_id FOREIGN KEY (order_id) REFERENCES public.orders(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.orders_products ADD CONSTRAINT orders_products_product_id_90f4ac8b_fk_product_id FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE INITIALLY DEFERRED;